thrift/matching.thrift
This patch adds a taskSource param to AddTask API request structs. The task source for now is either (1) history service or (2) matching db_backlog. This param will be used by the implementation of scalable task list i.e. when child partitions attempt remote-sync-match with parent partition, this info is needed to decide if certain operations can be performed.
=> matching: add taskSource param to addTask APIs

scripts/buildkite/fossa.sh
The latest fossa install script will also install https://github.com/fossas/spectrometer (https://github.com/fossas/fossa-cli/pull/568). However the script will install it to the default path `/usr/local/bin` where we don't have access to on buildkite agent. 
Fossa Issue for tracking: https://github.com/fossas/fossa-cli/issues/587
This pr ping fossa to an old version so that build can pass on buildkite.
=> Ping fossa version for fixing buildkite issue

scripts/buildkite/fossa.sh
https://github.com/uber/cadence-idl/pull/22 ping fossa to an old version as a temporarily workaround for https://github.com/fossas/fossa-cli/issues/587
Now that fossa team has fixed the issue, we can continue to use the latest install script and fossa release.
=> Use fossa install script from master

thrift/history.thrift, thrift/replicator.thrift
Add notify failover marker API thrift. This API uses to send the failover markers to the failover coordinator. The coordinator tracks the received marker and decides when to move the domain to active
=> Add notify failover marker API thrift

thrift/shared.thrift
For https://github.com/uber/cadence/issues/3556 
`skipSignalReapply` will allow skipping the reapplication of signals after reset point.
=> Add reset option: skipSignalReapply 

thrift/shared.thrift
Same changes with [this](https://github.com/uber/cadence-idl/commit/f21422c6183528f3e8c429595886020d60c58d72). Additionally, this will support delayed starts for child workflows and workflow starts
with retries and signal starts
=> Add delayStart to more workflow start structs

thrift/history.thrift
History.thrift changes for the new WorkflowExecutionAlreadyCompletedError were missing in this commit (https://github.com/uber/cadence-idl/pull/60). With this diff we also apply the new error to the idl branch.
**Why?**
=> Apply new error change to history.thrift

thrift/cadence.thrift, thrift/history.thrift
`WorkflowExecutionAlreadyCompletedError` was originally thought for SignalWorkflow, CancelWorkflow and TerminateWorkflow. To have a consistent behavior with consistent states from the other APIs, expanding this error to some other APIs.
See https://github.com/uber/cadence/pull/4123/ for more details.
Following functions support `EntityNotExistsError` but doesn't seem to need `WorkflowExecutionAlreadyCompletedError`. Please check the list below and let me know if we need to support the new error for some of those functions 
```
cadence.thrift:
- DescribeDomain
- ListDomains
- UpdateDomain
- DeprecateDomain
- GetWorkflowExecutionHistory ? 
- ListOpenWorkflowExecutions
- ListClosedWorkflowExecutions
- ListWorkflowExecutions
- ListArchivedWorkflowExecutions
- …
```
=> Expand workflowAlreadyCompletedError to other apis

proto/uber/cadence/api/v1/workflow.proto, thrift/shared.thrift
This field is needed so CLI commands for ElasticSearch can work properly. ListWorkflow calls share information between the server and client through WorkflowExecutionInfo
=> Add isCron field to WorkflowExecutionInfo

proto/uber/cadence/api/v1/service_worker.proto, proto/uber/cadence/api/v1/service_workflow.proto
A couple of RPCs were misplaced in the wrong service during initial api iteration.
- Move `RequestCancelWorkflowExecution` to `WorkflowService`. This is not part or the worker. User may cancel workflow execution from the client.
- Move `ResetStickyTaskList` to `WorkerService`. This is only used by the worker.
At this point we can still do this change. Clients are not yet released so we will not break them.
=> Switch proto rpcs between services

thrift/shared.thrift
- Add Workflow_Already_Completed and Uncategorized type for CrossClusterTaskFailed Cause
- Add per shard failed cause for getting cross cluster tasks
- Add fetchNewTasks bool field for indicating whether new tasks should be returned on responding task processing result
=> Improve definition for cross-cluster related endpoints

thrift/shared.thrift
Target cluster name is required for removing cross-cluster tasks
=> Add clusterName to RemoveTaskRequest

thrift/shared.thrift
Since the execution for a cross cluster task has multiple stages(e.g. for signal execution, there's a signal step and a remove signal mutable state step) and the fact that source cluster may send duplicated x-cluster task requests, we need to know what's the stage the x-cluster task response is for.
=> Add taskState to CrossClusterTaskResponse

thrift/matching.thrift
the data contract to dispatch activity tasks from history to matching before generating transfer tasks
=> add data contract for activity task dispatch

thrift/matching.thrift
We forgot to add this error to the exception lists in https://github.com/uber/cadence-idl/pull/109
=> Add StickyWorkerUnavailableError to exception list

thrift/sqlblobs.thrift
firstExecutionRunID should be binary type in thrift
fix https://github.com/uber/cadence-idl/pull/126
=> Fix firstExecutionRunID type for thrift blobs

thrift/indexer.thrift
Add new pinot message to publish message to Kafka. We can not use the existing message structure since pinot directly digest from Kafka topic, we have to flatten the message structure.
=> Add new pinot visibility message type

thrift/admin.thrift, thrift/shared.thrift, thrift/sqlblobs.thrift
- Moves the thrift shared components into the `shared` block
- Adds an entry to the domain persistence layer
=> corrects thrift changes to include persistence layer

thrift/shared.thrift
Adding fields for WorkflowExecutionInfo so we can have roundtrip conversion between internal types WorkflowExecutionInfo and thrift WorkflowExecutionInfo.
These fields exists in proto, but is missing in thrift.
=> [history] Sync internal WorkflowExecutionInfo with thrift shared

thrift/sqlblobs.thrift
Adding async workflow config to DomainInfo sql blob. This is needed to be able to persist a domain's async workflow config for sql persistence layers.
A follow up to #156.
=> Add async workflow config to DomainInfo sql blob

thrift/history.thrift, thrift/shared.thrift
This API is purely for inter-Cadence-service use, so the Protobuf equivalent is in the github.com/uber/cadence repository (where it is not randomly exposed to clients): https://github.com/uber/cadence/pull/5817
Design-wise: this has gone through several adjustment and experimenting rounds, and nearly all top-level keys I can come up with are either totally insufficient or totally unnecessary for one ratelimit design or another, so I've leaned more and more towards "define nothing, allow passing anything".
In the extreme, this means: just one `Any` field.  We can add more later if needed / if we discover some kind of truly universal data that is always worth including.
Obviously this is not super ergonomic, but as the ratelimiter is intended to be pluggable by outside implementations it …
=> Global ratelimiter, part 2: Any-typed global ratelimiting APIs for thrift

.buildkite/pipeline.yml
- Update Buildkite pipeline yaml to work with the newly provisioned queues in Google Kubernetes Engine
- Use [agent-stack-k8s v0.8.0 helm chart](https://github.com/buildkite/agent-stack-k8s/tree/v0.8.0?tab=readme-ov-file#cloning-repos-via-ssh) which has its own expected pipeline yaml syntax in order to successfully onboard. 
**Why?**
- There is a company mandate to evacuate Uber's AWS CI footprint. The go forward decision is to use Google Cloud. Buildkite Enterprise recommends GKE (as opposed to GCP) as the way to have a queue with autoscaling compute. 
- https://buildkite.com/uberopensource/cadence-idl/builds/518
- CI builds will be broken or flaky
- Can be mitigated by a git revert
n/a
**Documentation …
=> Migrate Buildkite CI queues from AWS to GKE

thrift/history.thrift
Mostly-prerequisite for the final major step of building the global ratelimiter system in https://github.com/uber/cadence/pull/6141
This Thrift addition _does not_ need to be done, the system could instead exchange Protobuf / gob / JSON data.  But I've done it in Thrift because:
1. We already use Thrift rather heavily in service code, for long-term-stable data, like many database types.
2. We do not use Protobuf like ^ this _anywhere_.  This PR could begin to change that, but I feel like that has some larger ramifications to discuss before leaping for it.
3. Gob is _significantly_ larger than Thrift, and no more human-readable than Thrift or Protobuf, and it doesn't offer quite as strong protection against unintended changes (IDL files/codegen make that "must be stable" contract very …
=> Global ratelimiter part 3: compact request-weighted-algorithm data

thrift/history.thrift
IDL changes needed to build https://github.com/uber/cadence/pull/6238
Basically this is just: return the "used RPS" that was already being tracked.
For compatibility purposes: while deploying, this will lead to version-crossing requests failing due to an unknown type, which will eventually put those keys into the "failing" mode.
This is currently _intended_, to serve as a full test of that fallback system, but should not be done in general.
Due to a different test (broken hashring) we have already seen the fallback system kick in correctly, so I'm fairly confident that this will work as intended.  Still, it's probably worth testing, particularly because it's easy.
---
This only changes thrift because this type is serialized _outside_ RPC, just like our database types.  There is no proto …
=> Add a usage-data return type to ratelimiters

thrift/matching.thrift, thrift/shared.thrift
Add a new error type so we can send the error from matching to history, such that history can handle the error more gracefully
This PR uses the change: https://github.com/uber/cadence/pull/6233 
No
- Added new exception in the thrift file. The corresponding error is added in proto in the main repo, as the is purely for internal usage. The exception's definition is: 
```
exception TaskListNotOwnedByHostError {
1: required string ownedByIdentity
2: required string myIdentity
3: required string tasklistName
}
```
- Added the exception as returned by all the matching API functions. 
- **Backward …
=> Add Tasklist not owned by host error, so we can propagate it internaally between matching and history 

thrift/cadence.thrift
We added AccessDeniedError to list of valid returned errors for all WorkflowService APIs. Currently all AccessDeniedError are being coded as unexpected error which is not the case.
- [] Add new API(s)
In this update, we are adding AccessDeniedError to the list of valid errors returned by all WorkflowService APIs. Previously, AccessDeniedError was being categorized as an unexpected error, which was inaccurate. As a result, the error handling system treated it as an unknown error, failing to recognize the intended "access-denied" response. With this change, AccessDeniedError will now be properly …
=> Add AccessDeniedError to every API endpoint in WorkflowService

thrift/shared.thrift, thrift/sqlblobs.thrift
Introduce queue states to shardInfo.
Define new data types representing the state of new version of history queue and store the new queue state in shard info blob.
- **Backward Compatibility**: Yes.
- **Forward Compatibility**: Yes.
- **Unit Tests**: Will have unit tests covered once merged into server repo.
- **Persistence Tests**: CRUD of the new data will be covered by persistence test.
- **Integration Tests**: Integration tests will be introduced when we implement the history queuev2 framework.
- **Compatibility Tests**: it's compatible
- What is the rollout plan? As usual.
- Does the order of deployment matter? No.
- Is it safe to rollback? Does the order of rollback matter? It's safe to rollback right now, but once we switch to queuev2 we cannot roll it back without rolling back …
=> Introduce data types for queue v2

thrift/sqlblobs.thrift
The new `activeClusterSelectionPolicy` field was defined as a typed field in sqlblobs however while doing the integration I noticed the data arrives to the corresponding sql persistence layer already serialized. So changing the type to blob. 
Not used anywhere yet so it's ok to remove/add new field.
- **Persistence Tests**: [If the change is related to a data type which is persisted, do we have …
=> Change active cluster policy to blob in sqlblobs

thrift/shared.thrift
This is a breaking change and we should revert it. It's ok to have this field required. 
This reverts commit f08e66d311941fb87f622c8b54fd5c64205a192d.
- **Persistence Tests**: [If the change is related to a data type which is persisted, do we have persistence tests covering the change?]
- **Integration Tests**: [Do we have integration test covering the change?]
- **Compatibility Tests**: [Have we done …
=> Revert "change from required to optional for EntityNotExistsError (#213)

Makefile
Updated the protobuf compiler version from 3.14.0 to 29.1. We also regenerate all Go protobuf files with the updated compiler version but no file changes observed, maintaining backward compatibility while providing access to newer protobuf capabilities.
No
Changes Made:
Updated PROTOC_VERSION in Makefile from 3.14.0 to 29.1
Fixed URL format for newer protobuf versions to use aarch_64 instead of arm64 for ARM64 architecture
Regenerated all protobuf Go files in both go/proto/api/v1/ and go/proto/admin/v1/ directories
Version Mapping:
- Protoc Version: 29.1
- Python Equivalent: 5.29.1
- Java …
=> Update protobuf version to 29.1 and regenerate all files
