thrift/checksum.thrift
=> add checksum.thrift

thrift/admin.thrift
Fix DLQ admin CLI to use request and response from replicator file
=> Fix DLQ admin CLI

thrift/shared.thrift
For fixing: https://github.com/uber/cadence/issues/3152
=> Add visibilityTimestamp to removeTask request

thrift/shared.thrift
prerequisite for https://github.com/uber/cadence/pull/3171
=> Add TaskList to WorkflowExecutionInfo

thrift/shared.thrift
Add failover timeout into updateDomainRequest
=> Add failover timeout into update domain request

thrift/shared.thrift
https://github.com/uber/cadence/issues/2653
=> Add TerminateIfRunning to WorkflowIdResuePolicy

thrift/replicator.thrift
Add version in metadata replication task to support a NDC task
=> Metadata task fix for ndc 

thrift/replicator.thrift
Cherry pick metadata task version idl changes
=> Add version to metadata task attributes

thrift/sqlblobs.thrift
Update Replication task info IDL for sql struct
=> Update Replication task info for sql

thrift/replicator.thrift, thrift/sqlblobs.thrift
Store the failover marker in DB as a data blob
=> Add pending failover marker in shard info

thrift/history.thrift, thrift/shared.thrift
as part of https://github.com/uber/cadence/pull/3609
=> Extend ScheduleActivityTask decision attributes with a requestLocalDispatch field

thrift/sqlblobs.thrift
Update sql blob domain last updated time
=> Update sql blob domain last updated time

thrift/replicator.thrift
Add creation time in replication time for latency metrics
=> Add creation time in replication time for latency metrics

thrift/shadower.thrift
Add java non retryable error type
=> Add java non retryable error type

thrift/shared.thrift
With this change StartWorkflowExecutionRequest will have the delay start
param so client can configure delay start
=> Introduce delay start parameter

thrift/cadence.thrift, thrift/shared.thrift
Introducing WorkflowAlreadyCompleted error in idl repo so it can be used between server client communication 
**Why?**
=> Introduce WorkflowAlreadyCompleted error type

thrift/admin.thrift
This helps to switch on and off advanced queries in UI automatically
=> Add persistence info to DescribeClusterResponse

proto/uber/cadence/api/v1/error.proto
Proto changes recently moved to idls folder, we need to add
WorkflowExecutionAlreadyCompleted error there too
=> Add workflow completed error to idls proto files

thrift/admin.thrift, thrift/history.thrift, thrift/shared.thrift
Prerequisite changes to adding CLI command to show history shard distribution
=> Add shard distribution command request/response

thrift/shared.thrift
Introducing FeatureFlags and FeatureNotEnabledError in IDL repo. These changes will help us ship breaking changes without affecting customer workflows
Review/Land order:
- IDL changes: uber/cadence-idl#73
- Client-side changes: https://github.com/uber-go/cadence-client/pull/1103
- Server-side changes: uber/cadence#4257
- Samples changes: uber-common/cadence-samples#45
=> Add IDL changes to support feature flags

proto/uber/cadence/api/v1/error.proto, proto/uber/cadence/api/v1/service_workflow.proto
Adding proto changes for the recently added feature flags structs: https://github.com/uber/cadence-idl/pull/73
=> Add proto changes for feature flags

thrift/admin.thrift, thrift/history.thrift, thrift/replicator.thrift, thrift/shared.thrift
Proto definition change will be done in the server repo since they are only used by cadence server
=> Add idl for fetching and responding cross cluster tasks

thrift/admin.thrift, thrift/config.thrift, thrift/configStore.thrift
Adds new thrift definitions for configStore API (Get, Update, Restore, List) as well as some internal types.
=> Changes for Config Store Support

thrift/cadence.thrift
Expose Admin Task Refresh API in client SDK
=> add refresh tasks API to workflow service

proto/uber/cadence/api/v1/service_workflow.proto
follow up on https://github.com/uber/cadence-idl/pull/102/files
=> add refresh tasks API to proto

thrift/matching.thrift
follow up https://github.com/uber/cadence-idl/pull/105/files
=> fixed ActivityTaskDispatchInfo field

thrift/indexer.thrift
Added new CREATE indexer message type for ElasticSearch bulk create request.
=> add new indexer message type

Makefile
Especially relevant here, as this module is almost solely concerned with codegen.
=> Adding a go-version warning message, like client and server repos

thrift/admin.thrift
Corrects a silly thrift mistake
=> Fix backwards thrift

thrift/admin.thrift
=> Add Get/Update domain async wf config to thrift admin api

thrift/sqlblobs.thrift
Update workflow execution info to store checksum
**Why?**
To store checksum in SQL database
=> Update workflow execution info to store checksum

thrift/cadence.thrift
Fix SignalWithStartWorkflowExecutionAsync API
**Why?**
=> Fix SignalWithStartWorkflowExecutionAsync API

thrift/shared.thrift
Add missing SignalWithStartWorkflowExecutionAsyncRequest
**Why?**
=> Add missing SignalWithStartWorkflowExecutionAsyncRequest

thrift/sqlblobs.thrift
Add new supported Async request type
**Why?**
To support new Async API
=> Add new supported Async request type

.github/pull_request_template.md
Add a pull request template for this repo.
- **Persistence Tests**: [If the change is related to a data type which is persisted, do we have persistence tests covering the change?]
- **Integration Tests**: [Do we have integration test covering the change?]
- **Compatibility Tests**: [Have we done tests to test the backward and forward compatibility?]
- What is the rollout plan?
- Does the order of deployment matter?
- Is it safe to rollback? Does the order of rollback matter?
- …
=> Add a pull request template for IDL changes

.buildkite/pipeline.yml
Fossa's being removed / decomm'd. Removing for now until we move to a replacement
We're blocked because of this in builds.
=> Remove deprecated fossa

thrift/sqlblobs.thrift
Add task list partition config data type and add it to tasklistinfo data blob
Adding TaskListPartitionConfig struct
Adding TaskListPartitionConfig as a new field to TaskListInfo struct
- **Backward Compatibility**: Adding a new data type and field is backward compatible.
- **Forward Compatibility**: It is forward compatible because thrift deserialization framework can handle blob containing a non existing field.
- **Unit Tests**: We'll have unit test once it's merged into server repo.
- **Persistence Tests**: The persistence tests for SQL covers this change.
- **Integration Tests**: No.
- **Compatibility Tests**: No.
- What is the rollout plan? Just treat it as a normal deployment.
- Does the order of deployment matter? No.
- Is it safe to rollback? Does the order of rollback matter? It's …
=> Add task list partition config

thrift/sqlblobs.thrift
Updating a recently introduced field from strictly typed object to a blob to be consistent with other similar recent fields.
Not used so compatible.
Not used so compatible.
- **Persistence Tests**: [If the change is related to a data type which is persisted, do we have persistence tests covering the change?]
- **Integration Tests**: [Do we have integration test covering the change?]
- **Compatibility …
=> Make activeclusters config a blob in sqlblobs

thrift/shared.thrift
Active cluster selection policy will be stored on
- execution rows: this is just to provide visibility in UI/CLI about the policy used to start the wf
- selection policy rows: this is going to be used when determining which cluster to forward the request to
- **Persistence Tests**: [If the change is related to a data type which is persisted, do we have persistence tests covering the change?]
- …
=> Add active cluster selection policy to execution info
